export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const SET_DEVICE_SUCCESS = 'SET_DEVICE_SUCCESS'
export const REG_SUCCESS = 'REG_SUCCESS'

// 项目相关
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS'
export const SAVE_USER_PROJECT_SUCCESS = 'SAVE_USER_PROJECT_SUCCESS'
export const DEL_USER_PROJECT_SUCCESS = 'DEL_USER_PROJECT_SUCCESS'
export const UPDATE_USER_PROJECT_SUCCESS = 'UPDATE_USER_PROJECT_SUCCESS'
export const ACTIVE_USER_PROJECT_SUCCESS = 'ACTIVE_USER_PROJECT_SUCCESS'

// 文件相关
export const GET_PROJECT_FOLDER_CHILDREN_REQUEST = 'GET_PROJECT_FOLDER_CHILDREN_REQUEST'
export const GET_PROJECT_FOLDER_CHILDREN_SUCCESS = 'GET_PROJECT_FOLDER_CHILDREN_SUCCESS'
export const GET_PROJECT_FOLDER_CHILDREN_BYID_SUCCESS = 'GET_PROJECT_FOLDER_CHILDREN_BYID_SUCCESS'
export const GET_PROJECT_FILES_SUCCESS = 'GET_PROJECT_FILES_SUCCESS'
export const GET_PROJECT_FILES_REQUEST = 'GET_PROJECT_FILES_REQUEST'
export const SAVE_PROJECT_FOLDER_SUCCESS = 'SAVE_PROJECT_FOLDER_SUCCESS'
export const DEL_PROJECT_FOLDER_SUCCESS = 'DEL_PROJECT_FOLDER_SUCCESS'
export const DEL_PROJECT_FILE_SUCCESS = 'DEL_PROJECT_FILE_SUCCESS'
export const UPDATE_PROJECT_FOLDER_SUCCESS = 'UPDATE_PROJECT_FOLDER_SUCCESS'
export const UPDATE_PROJECT_FILE_SUCCESS = 'UPDATE_PROJECT_FILE_SUCCESS'
export const GET_FOLDER_CHILDREN_SUCCESS = 'GET_FOLDER_CHILDREN_SUCCESS'
export const ACTIVE_PROJECT_FOLDER_SUCCESS = 'ACTIVE_PROJECT_FOLDER_SUCCESS'
export const ACTIVE_USER_PROJECT_BY_ID_SUCCESS = 'ACTIVE_USER_PROJECT_BY_ID_SUCCESS'
export const SET_PROJECT_FILES_INIT = 'SET_PROJECT_FILES_INIT'
export const GET_PROJECT_FILES_BY_ID_SUCCESS = 'GET_PROJECT_FILES_BY_ID_SUCCESS'
export const DEL_TREE_SUCCESS = 'DEL_TREE_SUCCESS'
export const SET_TREE_ACTIVE_ITEM_SUCCESS = 'SET_TREE_ACTIVE_ITEM_SUCCESS'
export const SAVE_TREE_ITEM_SUCCESS = 'SAVE_TREE_ITEM_SUCCESS'
export const GET_FILE_INFO_SUCCESS = 'GET_FILE_INFO_SUCCESS'
export const RESTORE_PROJECT_ITEM_SUCCESS = 'RESTORE_PROJECT_ITEM_SUCCESS'
export const CHECK_ALL_PROJECT_RECYCLE_SUCCESS = 'CHECK_ALL_PROJECT_RECYCLE_SUCCESS'
export const COPY_FILE_SUCCESS = 'COPY_FILE_SUCCESS'
export const GET_FILE_TYPE_SUCCESS = 'GET_FILE_TYPE_SUCCESS'
export const GET_PROJECT_FILES_MORE_SUCCESS = 'GET_PROJECT_FILES_MORE_SUCCESS'
export const GET_PROJECT_FILES_MORE_REQUEST = 'GET_PROJECT_FILES_MORE_REQUEST'
// 找到节点是否缓存
export const SEARCH_NODE_CACHE = 'SEARCH_NODE_CACHE'

// 回收站
export const GET_PROJECT_RECYCLE_SUCCESS = 'GET_PROJECT_RECYCLE_SUCCESS'
export const ADD_PROJECT_ITEMTO_RECYCLE_SUCCESS = 'ADD_PROJECT_ITEMTO_RECYCLE_SUCCESS'
export const RESTORE_PROJECT_RECYCLE_SUCCESS = 'RESTORE_PROJECT_RECYCLE_SUCCESS'

// 文件分享
export const GET_PROJECT_SHARE_SUCCESS = 'GET_PROJECT_SHARE_SUCCESS'
export const SHARE_PROJECT_FILE_SUCCESS = 'SHARE_PROJECT_FILE_SUCCESS'
export const DELETE_SHARED_RESOURCE_SUCCESS = 'DELETE_SHARED_RESOURCE_SUCCESS'
export const CREATE_SHARED_PUBLIC_URL_SUCCESS = 'CREATE_SHARED_PUBLIC_URL_SUCCESS'

// JOB
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS'

// 成员
export const GET_PROJECT_MEMBERS_SUCCESS = 'GET_PROJECT_MEMBERS_SUCCESS'
export const GET_PROJECT_MEMBER_INFO_SUCCESS = 'GET_PROJECT_MEMBER_INFO_SUCCESS'
export const SAVE_PROJECT_MEMBER_SUCCESS = 'SAVE_PROJECT_MEMBER_SUCCESS'
export const DEL_PROJECT_MEMBER = 'DEL_PROJECT_MEMBER'
export const DEL_PROJECT_MEMBER_ADMIN = 'DEL_PROJECT_MEMBER_ADMIN'
export const AUTH_PROJECT_MEMBER_ADMIN = 'AUTH_PROJECT_MEMBER_ADMIN'

// 分配Account
export const GET_BOX_SERVICE_ACCOUNT = 'GET_BOX_SERVICE_ACCOUNT'
export const NEW_BOX_SERVICE_ACCOUNT = 'NEW_BOX_SERVICE_ACCOUNT'

// navbar引用-----未定义
export const SET_SIDERBAR_ACTIVE_ITEM = 'SET_SIDERBAR_ACTIVE_ITEM'
export const GET_SIDERBAR = 'GET_SIDERBAR'

// 文件详情
export const DETAIL_INITIALIZATION = 'DETAIL_INITIALIZATION'
export const SHOW_ERROR_AND_TEXT = 'SHOW_ERROR_AND_TEXT'
export const GET_MINIFY_FOLDERS = 'GET_MINIFY_FOLDERS'

// 批注相关
export const LOAD_COMMIT_COMPONENTS = 'LOAD_COMMIT_COMPONENTS'
export const LOAD_COMMIT_FETCHING = 'LOAD_COMMIT_FETCHING'
export const LOAD_COMMENT_FILTERS = 'LOAD_COMMENT_FILTERS'
export const ACTIVE_COMMENT = 'ACTIVE_COMMENT'
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE'
export const SHIFT_STAR = 'SHIFT_STAR'
export const SHIFT_COMMENT_STATUS = 'SHIFT_COMMENT_STATUS'

export const GET_COMMENTS = 'GET_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

// 批注回复相关
export const ADD_RESPONSE = 'ADD_RESPONSE'
export const DELETE_RESPONSE = 'DELETE_RESPONSE'

// 拼装
export const GET_FILES_MODEL = 'GET_FILES_MODEL'
